#!/bin/bash -e

echo "resolver $(grep nameserver /etc/resolv.conf | awk '{print $2}') valid=5s;" > /etc/nginx/conf.d/resolver.conf

if [ "$SET_REAL_IP_FROM" ]; then
    echo "set_real_ip_from $SET_REAL_IP_FROM;" > /etc/nginx/conf.d/set_real_ip_from.conf
fi

exec /usr/sbin/nginx 2>&1
